name: sync
on:
  push: ~
  schedule:
  - cron: '0 3 * * 0'
jobs:
  sync:
    env:
      OAIPMH_URL: https://arche.acdh.oeaw.ac.at/oaipmh/#dha
      SPARQL_URL: https://triplestore.acdh-dev.oeaw.ac.at/dha-catalogue/sparql
      SPARQL_USER: dha-catalogue
      VOCABS_NMSP: https://vocabs.acdh.oeaw.ac.at/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.11
    #- uses: mxschmitt/action-tmate@v3
    - name: install
      run: poetry install --no-dev --no-root
    - name: synchronize
      run: poetry run dha-harvester --sparqlContinueOnFailure --verbose ${{ env.OAIPMH_URL }} ${{ env.SPARQL_URL }} --sparqlUser ${{ env.SPARQL_USER }} --sparqlPswd ${{ secrets.SPARQL_PSWD }}
    - name: vocabularies
      run: poetry run dha-vocabsharvester ${{ env.SPARQL_URL }} ${{ env.VOCABS_NMSP }} --sparqlUser ${{ env.SPARQL_USER }} --sparqlPswd ${{ secrets.SPARQL_PSWD }}
